### ISSUE TITLE
compiling error.

### ISSUE THREAD

**Issue by sergiojolly01** [ZulNs/STM32F1_RTC#5]
I ZulNs, 
I tried to compile the file Serial_Clock_and_Calendar, but the following error appear. It seams that the RCC_BDCR_RTC_BIT is not defined. If I define it, on the STM32F1_RTC.h, the error desapper, but the sketch does not work (I define it equal to 1, but my be the right value is different than 1). Do you have any idea how solve this issue? 
Thanks a lot for yuor support and best regards,
Sergio (ITALY)

:\Program Files (x86)\arduino-1.8.13\hardware\Arduino_STM32_08_10_2019\STM32F1\system/libmaple/stm32f1/include/series/r**cc.h:356:48: error: 'RCC_BDCR_RTC_BIT' was not declared in this scope
 #define RCC_BDCR_RTCEN                  (1U << RCC_BDCR_RTC_BIT)**
                                                ^
C:\Users\Sergio\Documents\LavoriSergio\MySoftwareSTM32\libraries\STM32F1_RTC-master\src\stm32f1_rtc.cpp:21:15: note: in expansion of macro 'RCC_BDCR_RTCEN'
   RCC_BDCR |= RCC_BDCR_RTCEN; // Enables the RTC

**Comment by ZulNs** [comment]
It seems that error was caused by a definition error in Roger Clark's libmaple. This error has been fixed in the latest version, but you can fix it yourself.
Please find the `rcc.h` file in folder `your_Arduino_project_folder\hardware\Arduino_STM32\STM32F1\system\libmaple\stm32f1\include\series` . Edit that file, go to line `356` and replace

`#define RCC_BDCR_RTCEN                  (1U << RCC_BDCR_RTC_BIT)`

with

`#define RCC_BDCR_RTCEN                  (1U << RCC_BDCR_RTCEN_BIT)`

To convince you, please compare yourself that above line with this [file](https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/system/libmaple/stm32f1/include/series/rcc.h).

Hope this help.

**Comment by sergiojolly01** [comment]
Dear ZuNS,
modified the file as your indication, now it compiles without errors.
I will inform Roger.
Thanks a lot for your support and best regards,
Sergio
